### PR TITLE
Fix changelog color in css.sty

### PR DESCRIPTION
**Pull request by mojca**
Here's my proposed change for the css.

We might additionally want to change something like
```css
h1:target, h2:target, h3:target, h4:target, h5:target, h6:target, span:target {
    background: #cddffa; /* color for testing only, shadow color needs to be adapted as well */
}
```
and maybe
```css
#changelog .comment, #ticketchange .comment {
    clear: right;
}
```

### CODE REVIEW

**Comment by raimue** [comment]
The border still appears to be yellow. The corresponding rule in the original ticket.css seems to be this one:

```
#changelog .changes, #ticketchange .changes {
    border-color: #eea #dd9 #dd9 #eea;
}
```

**Comment by raimue** [comment]
Scratch that last comment, as this change is not deployed yet.

But somehow the background of the `.changes` box in the preview when modifying a ticket was already not yellow anymore...

**Comment by neverpanic** [comment]
Make sure that your cache isn't playing tricks on you; you may still have the old CSS.

**Comment by raimue** [comment]
I deployed these changes and they are now live.

**Comment by mojca** [comment]
Thank you. It takes some cache clearing to see it, but now I noticed there's also greenish text inside the box which seems a bit weird in this gray box.

**Pull request merged**
